### ISSUE TITLE
Suggestion: Simplify video about getting the samples

### ISSUE THREAD

**Issue by michax** [planetoftheweb/angular2#2]
In your video you suggest to use bare repository which in my opinion is unnecessary.
To get remote branches it's enough to execute:

```
git branch -a
```

Then when using git checkout 02_08b, it will automatically setup upstream branch if found.
Nothing major. Just though that step was unnecessarily complicated.

Only explanation that i can think of is that in old versions of git, upstream is not setup automatically. But again, it will only be required if someone want's to push back changes.

Another useful thing to mention is to use 

```
git fetch 
```

to update list of branches and tags.

**Comment by planetoftheweb** [comment]
I think that's OK for a few branches, but most of the courses I do have 30 or more branches, so doing a bare repository lets you wire things up way quicker than doing them one by one.
