### ISSUE TITLE
i wish this  repo to be upgraded to latest (newer than current 2.0.0-beta.2) version of angular2

### ISSUE THREAD

**Issue by shootermv** [planetoftheweb/angular2#7]
I hope it will be good for tutorial too

**Comment by crewtec-cl** [comment]
+1!

Ray, plz help!

**Comment by planetoftheweb** [comment]
I created a new repo called [Learn Angular](https://github.com/planetoftheweb/learnangular) with the new version of the course, which is in editing.

**Comment by crewtec-cl** [comment]
Hello Ray,

thanks for your answer and sharing your work. 

No gulp in the new version? I will definitely need an explanation and more study. :(

Any probable date for the course?

Thanks a lot!
